name: Dynamic README Updater

on:
  schedule:
    - cron: '0 2 * * *'    # runs daily at 02:00 UTC (change if you want)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run README updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          python scripts/update_readme.py

      - name: Commit updated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update dynamic README & assets"
